#!/usr/bin/env bash
# Repeat generated harness fixtures and report baseline-subtracted timings.
#
# Defaults:
#   - benchmark the slowest MM2_BENCH_TOP=5 files from outputs/harness_perf.tsv
#     if it exists, otherwise a small built-in slow-file seed set
#   - run each fixture MM2_BENCH_RUNS=3 times, serially
#   - subtract an import+mm2-init baseline median from each fixture median
#
# Example:
#   bash scripts/bench-harness-corpus.sh test_forward_chainer test_particle_values

set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ROOT_DIR"
. scripts/harness-common.sh
validate_harness_floor_table || exit 2

runs="${MM2_BENCH_RUNS:-3}"
top_n="${MM2_BENCH_TOP:-5}"
timeout_s="${MM2_BENCH_TIMEOUT:-300}"
summary_report="${MM2_BENCH_OUT:-outputs/harness_bench.tsv}"
runs_report="${MM2_BENCH_RUNS_OUT:-outputs/harness_bench_runs.tsv}"

require_positive_int() {
  local name="$1"
  local value="$2"
  case "$value" in
    ''|*[!0-9]*)
      echo "$name must be a positive integer, got: $value" >&2
      exit 2
      ;;
  esac
  if [ "$value" -lt 1 ]; then
    echo "$name must be a positive integer, got: $value" >&2
    exit 2
  fi
}

require_positive_int MM2_BENCH_RUNS "$runs"
require_positive_int MM2_BENCH_TOP "$top_n"
require_positive_int MM2_BENCH_TIMEOUT "$timeout_s"

now_ns() {
  date +%s%N
}

median_ms() {
  printf '%s\n' "$@" |
    sort -n |
    awk '
      { values[NR] = $1 }
      END {
        if (NR == 0) {
          print 0
        } else if (NR % 2 == 1) {
          print values[(NR + 1) / 2]
        } else {
          print int((values[NR / 2] + values[NR / 2 + 1]) / 2)
        }
      }'
}

min_ms() {
  printf '%s\n' "$@" | sort -n | awk 'NR == 1 { print $1 }'
}

max_ms() {
  printf '%s\n' "$@" | sort -n | awk 'END { print $1 }'
}

fixture_path() {
  local requested="$1"
  case "$requested" in
    *.metta)
      printf '%s\n' "$requested"
      ;;
    *)
      printf 'tests/harness/generated/%s.metta\n' "$requested"
      ;;
  esac
}

default_fixtures() {
  if [ -s outputs/harness_perf.tsv ]; then
    awk -v n="$top_n" 'NR > 1 && seen < n { print $1; seen++ }' outputs/harness_perf.tsv
  else
    printf '%s\n' \
      test_forward_chainer \
      test_particle_values \
      test_forward_backward_compose \
      test_distribution_values \
      test_backward_dag_helpers
  fi
}

run_petta_file() {
  local file="$1"
  local name="$2"
  local run_id="$3"
  local log="$4"
  local vlog="$5"
  local start_ns end_ns duration_ms status count_log
  local pass close fail unsup_ir skipped omitted adapted

  : > "$vlog"
  start_ns="$(now_ns)"
  set +e
  MM2_HARNESS_VERDICT_LOG="$ROOT_DIR/$vlog" timeout "$timeout_s" petta "$file" > "$log" 2>&1
  status=$?
  set -e
  end_ns="$(now_ns)"
  duration_ms=$(((end_ns - start_ns) / 1000000))

  count_log="$log"
  if [ "$status" -ne 0 ]; then
    count_log="$vlog"
  fi
  pass="$(grep -c 'mm2-test-pass' "$count_log" || true)"
  close="$(grep -c 'mm2-test-close' "$count_log" || true)"
  fail="$(grep -c 'mm2-test-FAIL' "$count_log" || true)"
  unsup_ir="$(grep -c 'notsupported-ir' "$count_log" || true)"
  skipped="$(grep -c 'mm2-test-unsupported' "$count_log" || true)"
  omitted="$(grep -c '^; OMITTED' "$file" || true)"
  adapted="$(grep -c '^; ADAPTED' "$file" || true)"
  cat "$vlog" >> "$log"

  printf '%s\t%s\t%s\t%s\t%s\t%s\t%s\t%s\t%s\t%s\t%s\n' \
    "$name" "$run_id" "$duration_ms" "$pass" "$close" "$fail" "$unsup_ir" "$skipped" "$omitted" "$adapted" "$status"
}

mkdir -p outputs/harness_bench_logs "$(dirname "$summary_report")" "$(dirname "$runs_report")"
bash scripts/build-runtime.sh outputs/harness_runtime.mm2

tmp_dir="$(mktemp -d)"
trap 'rm -rf "$tmp_dir"' EXIT
baseline_file="$tmp_dir/mm2_harness_baseline.metta"
printf '%s\n' \
  '; generated by scripts/bench-harness-corpus.sh' \
  '!(import! &self /nexus/Dev/OpenCog/NL2PLN_Project/mm2-chainer/compiler/mm2_chainer)' \
  '!(mm2-init)' \
  > "$baseline_file"

if [ "$#" -eq 0 ]; then
  mapfile -t requested_fixtures < <(default_fixtures)
else
  requested_fixtures=("$@")
fi

if [ "${#requested_fixtures[@]}" -eq 0 ]; then
  echo "no benchmark fixtures selected" >&2
  exit 2
fi

files=()
for requested in "${requested_fixtures[@]}"; do
  candidate="$(fixture_path "$requested")"
  if [ ! -f "$candidate" ]; then
    echo "generated test not found: $requested" >&2
    exit 2
  fi
  files+=("$candidate")
done

for file in "${files[@]}"; do
  name="$(basename "$file" .metta)"
  min_pass="$(min_pass_for_file "$name")"
  if requires_harness_floor "$file" && [ "$min_pass" -le 0 ]; then
    echo "missing corpus pass floor for generated fixture: $name" >&2
    exit 2
  fi
done

baseline_times=()
printf 'file\trun\tduration_ms\tpass\tclose\tfail\tunsupported_ir\tskipped\tomitted\tadapted\tstatus\n' > "$runs_report"
for run_id in $(seq 1 "$runs"); do
  log="outputs/harness_bench_logs/__baseline.$run_id.log"
  vlog="outputs/harness_bench_logs/__baseline.$run_id.verdicts.log"
  row="$(run_petta_file "$baseline_file" __baseline "$run_id" "$log" "$vlog")"
  printf '%s\n' "$row" >> "$runs_report"
  IFS=$'\t' read -r _name _run duration_ms _pass _close _fail _unsup_ir _skipped _omitted _adapted status <<< "$row"
  if [ "$status" -ne 0 ]; then
    echo "baseline run $run_id failed with status $status; see $log" >&2
    exit 1
  fi
  baseline_times+=("$duration_ms")
done

baseline_median="$(median_ms "${baseline_times[@]}")"
summary_body="$tmp_dir/summary_body.tsv"
: > "$summary_body"
bench_errors=0

for file in "${files[@]}"; do
  name="$(basename "$file" .metta)"
  min_pass="$(min_pass_for_file "$name")"
  max_adapted="$(max_adapted_for_file "$name")"
  durations=()
  last_pass=0
  last_close=0
  last_fail=0
  last_unsup_ir=0
  last_skipped=0
  last_omitted=0
  last_adapted=0
  expected_pass=
  expected_close=
  expected_fail=
  expected_unsup_ir=
  expected_skipped=
  expected_omitted=
  expected_adapted=
  worst_status=0

  for run_id in $(seq 1 "$runs"); do
    log="outputs/harness_bench_logs/$name.$run_id.log"
    vlog="outputs/harness_bench_logs/$name.$run_id.verdicts.log"
    row="$(run_petta_file "$file" "$name" "$run_id" "$log" "$vlog")"
    printf '%s\n' "$row" >> "$runs_report"
    IFS=$'\t' read -r _name _run duration_ms pass close fail unsup_ir skipped omitted adapted status <<< "$row"
    durations+=("$duration_ms")
    last_pass="$pass"
    last_close="$close"
    last_fail="$fail"
    last_unsup_ir="$unsup_ir"
    last_skipped="$skipped"
    last_omitted="$omitted"
    last_adapted="$adapted"
    if [ "$status" -ne 0 ]; then
      worst_status="$status"
    fi
    if [ "$run_id" -eq 1 ]; then
      expected_pass="$pass"
      expected_close="$close"
      expected_fail="$fail"
      expected_unsup_ir="$unsup_ir"
      expected_skipped="$skipped"
      expected_omitted="$omitted"
      expected_adapted="$adapted"
    elif [ "$pass" -ne "$expected_pass" ] ||
         [ "$close" -ne "$expected_close" ] ||
         [ "$fail" -ne "$expected_fail" ] ||
         [ "$unsup_ir" -ne "$expected_unsup_ir" ] ||
         [ "$skipped" -ne "$expected_skipped" ] ||
         [ "$omitted" -ne "$expected_omitted" ] ||
         [ "$adapted" -ne "$expected_adapted" ]; then
      printf 'benchmark verdict counts varied for %s run %s: got pass=%s close=%s fail=%s unsupported-ir=%s skipped=%s omitted=%s adapted=%s; expected pass=%s close=%s fail=%s unsupported-ir=%s skipped=%s omitted=%s adapted=%s\n' \
        "$name" "$run_id" \
        "$pass" "$close" "$fail" "$unsup_ir" "$skipped" "$omitted" "$adapted" \
        "$expected_pass" "$expected_close" "$expected_fail" "$expected_unsup_ir" "$expected_skipped" "$expected_omitted" "$expected_adapted" >&2
      bench_errors=$((bench_errors + 1))
    fi
    if [ "$status" -ne 0 ] ||
       [ "$close" -ne 0 ] ||
       [ "$fail" -ne 0 ] ||
       [ "$unsup_ir" -ne 0 ] ||
       [ "$skipped" -ne 0 ] ||
       [ "$omitted" -ne 0 ] ||
       [ "$adapted" -gt "$max_adapted" ]; then
      bench_errors=$((bench_errors + 1))
    fi
    if [ "$pass" -lt "$min_pass" ]; then
      echo "benchmark pass count regressed for $name run $run_id: got $pass, expected at least $min_pass" >&2
      bench_errors=$((bench_errors + 1))
    fi
  done

  gross_median="$(median_ms "${durations[@]}")"
  gross_min="$(min_ms "${durations[@]}")"
  gross_max="$(max_ms "${durations[@]}")"
  net_median=$((gross_median - baseline_median))
  if [ "$net_median" -lt 0 ]; then
    net_median=0
  fi

  printf '%s\t%s\t%s\t%s\t%s\t%s\t%s\t%s\t%s\t%s\t%s\t%s\t%s\t%s\t%s\t%s\n' \
    "$name" "$runs" "$baseline_median" "$gross_median" "$net_median" \
    "$gross_min" "$gross_max" "$last_pass" "$min_pass" "$last_close" "$last_fail" \
    "$last_unsup_ir" "$last_skipped" "$last_omitted" "$last_adapted" "$worst_status" \
    >> "$summary_body"
done

{
  printf 'file\truns\tbaseline_median_ms\tgross_median_ms\tnet_median_ms\tgross_min_ms\tgross_max_ms\tpass\tmin_pass\tclose\tfail\tunsupported_ir\tskipped\tomitted\tadapted\tstatus\n'
  sort -t $'\t' -k5,5nr "$summary_body"
} > "$summary_report"

cat "$summary_report"
echo "wrote per-run timings to $runs_report"

if [ "$bench_errors" -ne 0 ]; then
  echo "benchmark saw $bench_errors non-clean fixture run(s)" >&2
  exit 1
fi
