#!/usr/bin/env bash
# Benchmark synthetic backward query workloads at configurable sizes.
#
# Defaults:
#   - run each case MM2_QUERY_BENCH_RUNS=3 times
#   - benchmark implication query depths 4, 8, and 12
#   - benchmark same-order And projection widths 4 and 8
#   - subtract an import+mm2-init baseline median from each case median
#   - record in-process query time by wrapping only mm2-query in current-time
#
# Example:
#   bash scripts/bench-query-scale.sh
#   MM2_QUERY_BENCH_CHAIN_DEPTHS="4 8 12 16" MM2_QUERY_BENCH_AND_WIDTHS="4 8 12" bash scripts/bench-query-scale.sh

set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ROOT_DIR"

runs="${MM2_QUERY_BENCH_RUNS:-3}"
timeout_s="${MM2_QUERY_BENCH_TIMEOUT:-300}"
chain_depths="${MM2_QUERY_BENCH_CHAIN_DEPTHS:-4 8 12}"
and_widths="${MM2_QUERY_BENCH_AND_WIDTHS:-4 8}"
summary_report="${MM2_QUERY_BENCH_OUT:-outputs/query_scale_bench.tsv}"
runs_report="${MM2_QUERY_BENCH_RUNS_OUT:-outputs/query_scale_bench_runs.tsv}"
lock_dir="outputs/.bench-query-scale.lock"
tmp_dir=""

require_positive_int() {
  local name="$1"
  local value="$2"
  case "$value" in
    ''|*[!0-9]*)
      echo "$name must be a positive integer, got: $value" >&2
      exit 2
      ;;
  esac
  if [ "$value" -lt 1 ]; then
    echo "$name must be a positive integer, got: $value" >&2
    exit 2
  fi
}

require_positive_int_list() {
  local name="$1"
  local values="$2"
  local found=0
  local value
  for value in $values; do
    require_positive_int "$name" "$value"
    found=1
  done
  if [ "$found" -ne 1 ]; then
    echo "$name must contain at least one positive integer" >&2
    exit 2
  fi
}

now_ns() {
  date +%s%N
}

median_ms() {
  printf '%s\n' "$@" |
    sort -n |
    awk '
      { values[NR] = $1 }
      END {
        if (NR == 0) {
          print 0
        } else if (NR % 2 == 1) {
          print values[(NR + 1) / 2]
        } else {
          print int((values[NR / 2] + values[NR / 2 + 1]) / 2)
        }
      }'
}

min_ms() {
  printf '%s\n' "$@" | sort -n | awk 'NR == 1 { print $1 }'
}

max_ms() {
  printf '%s\n' "$@" | sort -n | awk 'END { print $1 }'
}

cleanup() {
  if [ -n "$tmp_dir" ]; then
    rm -rf "$tmp_dir"
  fi
  rm -rf "$lock_dir"
}

emit_header() {
  printf '!(import! &self %s/compiler/mm2_chainer)\n' "$ROOT_DIR"
  printf '!(mm2-init)\n'
}

generate_baseline_fixture() {
  local file="$1"
  {
    printf '; generated by scripts/bench-query-scale.sh\n'
    emit_header
  } > "$file"
}

generate_chain_fixture() {
  local depth="$1"
  local file="$2"
  local steps=$((depth * 10))
  local case_name="query_chain_$depth"
  local i prev

  {
    printf '; generated query-chain-depth=%s by scripts/bench-query-scale.sh\n' "$depth"
    printf '; query steps=%s\n' "$steps"
    emit_header
    printf '!(mm2-compileadd queryScaleChain%sKb (: seed (QueryScaleNode0 item) (STV 1.0 1.0)))\n' "$depth"
    for i in $(seq 1 "$depth"); do
      prev=$((i - 1))
      printf '!(mm2-compileadd queryScaleChain%sKb (: r%s (Implication (Premises (QueryScaleNode%s $x)) (Conclusions (QueryScaleNode%s $x))) (CTV (STV 1.0 1.0) (STV 0.0 1.0))))\n' \
        "$depth" "$i" "$prev" "$i"
    done
    printf '!(let* (($t0 (current-time)) ($result (mm2-query %s queryScaleChain%sKb (: $prf (QueryScaleNode%s item) $tv))) ($t1 (current-time))) (if (not (== $result ())) (mm2-query-bench %s chain %s seconds (- $t1 $t0) mm2-test-pass) (mm2-query-bench %s chain %s seconds (- $t1 $t0) mm2-test-FAIL)))\n' \
      "$steps" "$depth" "$depth" "$case_name" "$depth" "$case_name" "$depth"
  } > "$file"
}

generate_and_projection_fixture() {
  local width="$1"
  local file="$2"
  local case_name="query_and_projection_$width"
  local i

  {
    printf '; generated and-projection-width=%s by scripts/bench-query-scale.sh\n' "$width"
    emit_header
    printf '!(mm2-compileadd queryScaleAnd%sKb (: fact (And' "$width"
    for i in $(seq 1 "$width"); do
      printf ' (QueryScalePart%s item)' "$i"
    done
    printf ') (STV 1.0 0.99)))\n'
    printf '!(let* (($t0 (current-time)) ($result (mm2-query 100 queryScaleAnd%sKb (: $prf (And' "$width"
    for i in $(seq 1 "$width"); do
      printf ' (QueryScalePart%s $x)' "$i"
    done
    printf ') $tv))) ($t1 (current-time))) (if (not (== $result ())) (mm2-query-bench %s and_projection %s seconds (- $t1 $t0) mm2-test-pass) (mm2-query-bench %s and_projection %s seconds (- $t1 $t0) mm2-test-FAIL)))\n' \
      "$case_name" "$width" "$case_name" "$width"
  } > "$file"
}

run_petta_file() {
  local file="$1"
  local name="$2"
  local shape="$3"
  local size="$4"
  local run_id="$5"
  local log="$6"
  local start_ns end_ns duration_ms status
  local pass close fail unsup_ir skipped
  local query_seconds query_ms

  start_ns="$(now_ns)"
  set +e
  timeout "$timeout_s" petta "$file" > "$log" 2>&1
  status=$?
  set -e
  end_ns="$(now_ns)"
  duration_ms=$(((end_ns - start_ns) / 1000000))

  pass="$(grep -c 'mm2-test-pass' "$log" || true)"
  close="$(grep -c 'mm2-test-close' "$log" || true)"
  fail="$(grep -c 'mm2-test-FAIL' "$log" || true)"
  unsup_ir="$(grep -c 'notsupported-ir' "$log" || true)"
  skipped="$(grep -c 'mm2-test-unsupported' "$log" || true)"
  query_seconds="$(
    sed -n 's/.*(mm2-query-bench [^ ]* [^ ]* [^ ]* seconds \([^ ]*\) .*/\1/p' "$log" |
      tail -n 1
  )"
  if [ -n "$query_seconds" ]; then
    query_ms="$(awk -v seconds="$query_seconds" 'BEGIN { printf "%d", (seconds * 1000) + 0.5 }')"
  else
    query_ms=0
  fi

  printf '%s\t%s\t%s\t%s\t%s\t%s\t%s\t%s\t%s\t%s\t%s\t%s\n' \
    "$name" "$shape" "$size" "$run_id" "$duration_ms" "$query_ms" "$pass" "$close" "$fail" "$unsup_ir" "$skipped" "$status"
}

require_positive_int MM2_QUERY_BENCH_RUNS "$runs"
require_positive_int MM2_QUERY_BENCH_TIMEOUT "$timeout_s"
require_positive_int_list MM2_QUERY_BENCH_CHAIN_DEPTHS "$chain_depths"
require_positive_int_list MM2_QUERY_BENCH_AND_WIDTHS "$and_widths"

mkdir -p outputs
if ! mkdir "$lock_dir" 2>/dev/null; then
  echo "another query scale benchmark appears to be running; remove $lock_dir if this is stale" >&2
  exit 2
fi
trap cleanup EXIT

mkdir -p outputs/query_scale_bench_logs "$(dirname "$summary_report")" "$(dirname "$runs_report")"
bash scripts/build-runtime.sh outputs/harness_runtime.mm2

tmp_dir="$(mktemp -d)"

baseline_file="$tmp_dir/baseline.metta"
generate_baseline_fixture "$baseline_file"

baseline_times=()
printf 'case\tshape\tsize\trun\tduration_ms\tquery_ms\tpass\tclose\tfail\tunsupported_ir\tskipped\tstatus\n' > "$runs_report"
for run_id in $(seq 1 "$runs"); do
  log="outputs/query_scale_bench_logs/__baseline.$run_id.log"
  row="$(run_petta_file "$baseline_file" __baseline baseline 0 "$run_id" "$log")"
  printf '%s\n' "$row" >> "$runs_report"
  IFS=$'\t' read -r _name _shape _size _run duration_ms _query_ms _pass _close _fail _unsup_ir _skipped status <<< "$row"
  if [ "$status" -ne 0 ]; then
    echo "baseline run $run_id failed with status $status; see $log" >&2
    exit 1
  fi
  baseline_times+=("$duration_ms")
done

baseline_median="$(median_ms "${baseline_times[@]}")"
summary_body="$tmp_dir/summary_body.tsv"
: > "$summary_body"
bench_errors=0

run_case() {
  local name="$1"
  local shape="$2"
  local size="$3"
  local file="$4"
  local durations=()
  local query_durations=()
  local last_pass=0
  local last_close=0
  local last_fail=0
  local last_unsup_ir=0
  local last_skipped=0
  local expected_pass=
  local expected_close=
  local expected_fail=
  local expected_unsup_ir=
  local expected_skipped=
  local worst_status=0
  local run_id row duration_ms query_ms pass close fail unsup_ir skipped status
  local gross_median gross_min gross_max net_median query_median query_min query_max log

  for run_id in $(seq 1 "$runs"); do
    log="outputs/query_scale_bench_logs/$name.$run_id.log"
    row="$(run_petta_file "$file" "$name" "$shape" "$size" "$run_id" "$log")"
    printf '%s\n' "$row" >> "$runs_report"
    IFS=$'\t' read -r _name _shape _size _run duration_ms query_ms pass close fail unsup_ir skipped status <<< "$row"
    durations+=("$duration_ms")
    query_durations+=("$query_ms")
    last_pass="$pass"
    last_close="$close"
    last_fail="$fail"
    last_unsup_ir="$unsup_ir"
    last_skipped="$skipped"
    if [ "$status" -ne 0 ]; then
      worst_status="$status"
    fi
    if [ "$run_id" -eq 1 ]; then
      expected_pass="$pass"
      expected_close="$close"
      expected_fail="$fail"
      expected_unsup_ir="$unsup_ir"
      expected_skipped="$skipped"
    elif [ "$pass" -ne "$expected_pass" ] ||
         [ "$close" -ne "$expected_close" ] ||
         [ "$fail" -ne "$expected_fail" ] ||
         [ "$unsup_ir" -ne "$expected_unsup_ir" ] ||
         [ "$skipped" -ne "$expected_skipped" ]; then
      printf 'query benchmark verdict counts varied for %s run %s: got pass=%s close=%s fail=%s unsupported-ir=%s skipped=%s; expected pass=%s close=%s fail=%s unsupported-ir=%s skipped=%s\n' \
        "$name" "$run_id" "$pass" "$close" "$fail" "$unsup_ir" "$skipped" \
        "$expected_pass" "$expected_close" "$expected_fail" "$expected_unsup_ir" "$expected_skipped" >&2
      bench_errors=$((bench_errors + 1))
    fi
    if [ "$status" -ne 0 ] ||
       [ "$pass" -le 0 ] ||
       [ "$close" -ne 0 ] ||
       [ "$fail" -ne 0 ] ||
       [ "$unsup_ir" -ne 0 ] ||
       [ "$skipped" -ne 0 ]; then
      bench_errors=$((bench_errors + 1))
    fi
  done

  gross_median="$(median_ms "${durations[@]}")"
  gross_min="$(min_ms "${durations[@]}")"
  gross_max="$(max_ms "${durations[@]}")"
  query_median="$(median_ms "${query_durations[@]}")"
  query_min="$(min_ms "${query_durations[@]}")"
  query_max="$(max_ms "${query_durations[@]}")"
  net_median=$((gross_median - baseline_median))
  if [ "$net_median" -lt 0 ]; then
    net_median=0
  fi

  printf '%s\t%s\t%s\t%s\t%s\t%s\t%s\t%s\t%s\t%s\t%s\t%s\t%s\t%s\t%s\t%s\t%s\t%s\n' \
    "$name" "$shape" "$size" "$runs" "$baseline_median" "$gross_median" "$net_median" \
    "$gross_min" "$gross_max" "$query_median" "$query_min" "$query_max" \
    "$last_pass" "$last_close" "$last_fail" "$last_unsup_ir" "$last_skipped" \
    "$worst_status" >> "$summary_body"
}

for depth in $chain_depths; do
  case_name="query_chain_$depth"
  fixture="$tmp_dir/$case_name.metta"
  generate_chain_fixture "$depth" "$fixture"
  run_case "$case_name" chain "$depth" "$fixture"
done

for width in $and_widths; do
  case_name="query_and_projection_$width"
  fixture="$tmp_dir/$case_name.metta"
  generate_and_projection_fixture "$width" "$fixture"
  run_case "$case_name" and_projection "$width" "$fixture"
done

{
  printf 'case\tshape\tsize\truns\tbaseline_median_ms\tgross_median_ms\tnet_median_ms\tgross_min_ms\tgross_max_ms\tquery_median_ms\tquery_min_ms\tquery_max_ms\tpass\tclose\tfail\tunsupported_ir\tskipped\tstatus\n'
  sort -t $'\t' -k10,10nr "$summary_body"
} > "$summary_report"

cat "$summary_report"
echo "wrote per-run timings to $runs_report"

if [ "$bench_errors" -ne 0 ]; then
  echo "query benchmark saw $bench_errors non-clean run(s)" >&2
  exit 1
fi
