#!/usr/bin/env bash
# Benchmark synthetic forward materialization at configurable chain/fanout sizes.
#
# Defaults:
#   - run each case MM2_FORWARD_BENCH_RUNS=3 times
#   - benchmark chain lengths 8 and 16
#   - benchmark fanout widths 16 and 64
#   - subtract an import+mm2-init baseline median from each case median
#
# Example:
#   bash scripts/bench-forward-scale.sh
#   MM2_FORWARD_BENCH_CHAIN_LENGTHS="8 16 32" MM2_FORWARD_BENCH_FANOUT_WIDTHS="32 128" bash scripts/bench-forward-scale.sh

set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ROOT_DIR"

runs="${MM2_FORWARD_BENCH_RUNS:-3}"
timeout_s="${MM2_FORWARD_BENCH_TIMEOUT:-300}"
chain_lengths="${MM2_FORWARD_BENCH_CHAIN_LENGTHS:-8 16}"
fanout_widths="${MM2_FORWARD_BENCH_FANOUT_WIDTHS:-16 64}"
summary_report="${MM2_FORWARD_BENCH_OUT:-outputs/forward_scale_bench.tsv}"
runs_report="${MM2_FORWARD_BENCH_RUNS_OUT:-outputs/forward_scale_bench_runs.tsv}"

require_positive_int() {
  local name="$1"
  local value="$2"
  case "$value" in
    ''|*[!0-9]*)
      echo "$name must be a positive integer, got: $value" >&2
      exit 2
      ;;
  esac
  if [ "$value" -lt 1 ]; then
    echo "$name must be a positive integer, got: $value" >&2
    exit 2
  fi
}

require_positive_int_list() {
  local name="$1"
  local values="$2"
  local found=0
  local value
  for value in $values; do
    require_positive_int "$name" "$value"
    found=1
  done
  if [ "$found" -ne 1 ]; then
    echo "$name must contain at least one positive integer" >&2
    exit 2
  fi
}

now_ns() {
  date +%s%N
}

median_ms() {
  printf '%s\n' "$@" |
    sort -n |
    awk '
      { values[NR] = $1 }
      END {
        if (NR == 0) {
          print 0
        } else if (NR % 2 == 1) {
          print values[(NR + 1) / 2]
        } else {
          print int((values[NR / 2] + values[NR / 2 + 1]) / 2)
        }
      }'
}

min_ms() {
  printf '%s\n' "$@" | sort -n | awk 'NR == 1 { print $1 }'
}

max_ms() {
  printf '%s\n' "$@" | sort -n | awk 'END { print $1 }'
}

emit_header() {
  printf '!(import! &self %s/compiler/mm2_chainer)\n' "$ROOT_DIR"
  printf '!(mm2-init)\n'
}

generate_baseline_fixture() {
  local file="$1"
  {
    printf '; generated by scripts/bench-forward-scale.sh\n'
    emit_header
  } > "$file"
}

generate_chain_fixture() {
  local length="$1"
  local file="$2"
  local rounds=$((length * 2))
  local i prev

  {
    printf '; generated chain-length=%s by scripts/bench-forward-scale.sh\n' "$length"
    emit_header
    printf '!(mm2-compileadd forwardScaleChain%sKb (: seed (ForwardScaleNode n0) (STV 1.0 1.0)))\n' "$length"
    for i in $(seq 1 "$length"); do
      prev=$((i - 1))
      printf '!(mm2-compileadd forwardScaleChain%sKb (: r%s (Implication (Premises (ForwardScaleNode n%s)) (Conclusions (ForwardScaleNode n%s))) (CTV (STV 1.0 1.0) (STV 0.0 1.0))))\n' \
        "$length" "$i" "$prev" "$i"
    done
    printf '!(mm2-test-forward-has-derived %s forwardScaleChain%sKb (ForwardScaleNode n%s) true)\n' \
      "$rounds" "$length" "$length"
  } > "$file"
}

generate_fanout_fixture() {
  local width="$1"
  local file="$2"
  local rounds=$(((width + 31) / 32))
  local i

  {
    printf '; generated fanout-width=%s by scripts/bench-forward-scale.sh\n' "$width"
    printf '; fanout rounds=%s\n' "$rounds"
    emit_header
    printf '!(mm2-compileadd forwardScaleFanout%sKb (: seed (ForwardScaleFanSeed) (STV 1.0 1.0)))\n' "$width"
    for i in $(seq 1 "$width"); do
      printf '!(mm2-compileadd forwardScaleFanout%sKb (: r%s (Implication (Premises (ForwardScaleFanSeed)) (Conclusions (ForwardScaleFanGoal g%s))) (CTV (STV 1.0 1.0) (STV 0.0 1.0))))\n' \
        "$width" "$i" "$i"
    done
    printf '!(mm2-test-equal (let* (($facts (collapse (match &kb ((ForwardScaleFanSeed) (forwardScaleFanout%sKb MAIN Nil) $prf $tv) ((ForwardScaleFanSeed) (forwardScaleFanout%sKb MAIN Nil) $prf $tv)))) ($_ (mm2-forward-chain-from-facts %s forwardScaleFanout%sKb $facts)) ($derived (collapse (match &kb ((ForwardScaleFanGoal $g) (forwardScaleFanout%sKb MAIN Nil) $prf $tv) $g)))) (list-count $derived)) %s)\n' \
      "$width" "$width" "$rounds" "$width" "$width" "$width"
  } > "$file"
}

run_petta_file() {
  local file="$1"
  local name="$2"
  local shape="$3"
  local size="$4"
  local run_id="$5"
  local log="$6"
  local start_ns end_ns duration_ms status
  local pass close fail unsup_ir skipped

  start_ns="$(now_ns)"
  set +e
  timeout "$timeout_s" petta "$file" > "$log" 2>&1
  status=$?
  set -e
  end_ns="$(now_ns)"
  duration_ms=$(((end_ns - start_ns) / 1000000))

  pass="$(grep -c 'mm2-test-pass' "$log" || true)"
  close="$(grep -c 'mm2-test-close' "$log" || true)"
  fail="$(grep -c 'mm2-test-FAIL' "$log" || true)"
  unsup_ir="$(grep -c 'notsupported-ir' "$log" || true)"
  skipped="$(grep -c 'mm2-test-unsupported' "$log" || true)"

  printf '%s\t%s\t%s\t%s\t%s\t%s\t%s\t%s\t%s\t%s\t%s\n' \
    "$name" "$shape" "$size" "$run_id" "$duration_ms" "$pass" "$close" "$fail" "$unsup_ir" "$skipped" "$status"
}

require_positive_int MM2_FORWARD_BENCH_RUNS "$runs"
require_positive_int MM2_FORWARD_BENCH_TIMEOUT "$timeout_s"
require_positive_int_list MM2_FORWARD_BENCH_CHAIN_LENGTHS "$chain_lengths"
require_positive_int_list MM2_FORWARD_BENCH_FANOUT_WIDTHS "$fanout_widths"

mkdir -p outputs/forward_scale_bench_logs "$(dirname "$summary_report")" "$(dirname "$runs_report")"
bash scripts/build-runtime.sh outputs/harness_runtime.mm2

tmp_dir="$(mktemp -d)"
trap 'rm -rf "$tmp_dir"' EXIT

baseline_file="$tmp_dir/baseline.metta"
generate_baseline_fixture "$baseline_file"

baseline_times=()
printf 'case\tshape\tsize\trun\tduration_ms\tpass\tclose\tfail\tunsupported_ir\tskipped\tstatus\n' > "$runs_report"
for run_id in $(seq 1 "$runs"); do
  log="outputs/forward_scale_bench_logs/__baseline.$run_id.log"
  row="$(run_petta_file "$baseline_file" __baseline baseline 0 "$run_id" "$log")"
  printf '%s\n' "$row" >> "$runs_report"
  IFS=$'\t' read -r _name _shape _size _run duration_ms _pass _close _fail _unsup_ir _skipped status <<< "$row"
  if [ "$status" -ne 0 ]; then
    echo "baseline run $run_id failed with status $status; see $log" >&2
    exit 1
  fi
  baseline_times+=("$duration_ms")
done

baseline_median="$(median_ms "${baseline_times[@]}")"
summary_body="$tmp_dir/summary_body.tsv"
: > "$summary_body"
bench_errors=0

run_case() {
  local name="$1"
  local shape="$2"
  local size="$3"
  local file="$4"
  local durations=()
  local last_pass=0
  local last_close=0
  local last_fail=0
  local last_unsup_ir=0
  local last_skipped=0
  local expected_pass=
  local expected_close=
  local expected_fail=
  local expected_unsup_ir=
  local expected_skipped=
  local worst_status=0
  local run_id row duration_ms pass close fail unsup_ir skipped status
  local gross_median gross_min gross_max net_median log

  for run_id in $(seq 1 "$runs"); do
    log="outputs/forward_scale_bench_logs/$name.$run_id.log"
    row="$(run_petta_file "$file" "$name" "$shape" "$size" "$run_id" "$log")"
    printf '%s\n' "$row" >> "$runs_report"
    IFS=$'\t' read -r _name _shape _size _run duration_ms pass close fail unsup_ir skipped status <<< "$row"
    durations+=("$duration_ms")
    last_pass="$pass"
    last_close="$close"
    last_fail="$fail"
    last_unsup_ir="$unsup_ir"
    last_skipped="$skipped"
    if [ "$status" -ne 0 ]; then
      worst_status="$status"
    fi
    if [ "$run_id" -eq 1 ]; then
      expected_pass="$pass"
      expected_close="$close"
      expected_fail="$fail"
      expected_unsup_ir="$unsup_ir"
      expected_skipped="$skipped"
    elif [ "$pass" -ne "$expected_pass" ] ||
         [ "$close" -ne "$expected_close" ] ||
         [ "$fail" -ne "$expected_fail" ] ||
         [ "$unsup_ir" -ne "$expected_unsup_ir" ] ||
         [ "$skipped" -ne "$expected_skipped" ]; then
      printf 'forward benchmark verdict counts varied for %s run %s: got pass=%s close=%s fail=%s unsupported-ir=%s skipped=%s; expected pass=%s close=%s fail=%s unsupported-ir=%s skipped=%s\n' \
        "$name" "$run_id" "$pass" "$close" "$fail" "$unsup_ir" "$skipped" \
        "$expected_pass" "$expected_close" "$expected_fail" "$expected_unsup_ir" "$expected_skipped" >&2
      bench_errors=$((bench_errors + 1))
    fi
    if [ "$status" -ne 0 ] ||
       [ "$pass" -le 0 ] ||
       [ "$close" -ne 0 ] ||
       [ "$fail" -ne 0 ] ||
       [ "$unsup_ir" -ne 0 ] ||
       [ "$skipped" -ne 0 ]; then
      bench_errors=$((bench_errors + 1))
    fi
  done

  gross_median="$(median_ms "${durations[@]}")"
  gross_min="$(min_ms "${durations[@]}")"
  gross_max="$(max_ms "${durations[@]}")"
  net_median=$((gross_median - baseline_median))
  if [ "$net_median" -lt 0 ]; then
    net_median=0
  fi

  printf '%s\t%s\t%s\t%s\t%s\t%s\t%s\t%s\t%s\t%s\t%s\t%s\t%s\t%s\t%s\n' \
    "$name" "$shape" "$size" "$runs" "$baseline_median" "$gross_median" "$net_median" \
    "$gross_min" "$gross_max" "$last_pass" "$last_close" "$last_fail" "$last_unsup_ir" "$last_skipped" \
    "$worst_status" >> "$summary_body"
}

for length in $chain_lengths; do
  case_name="forward_chain_$length"
  fixture="$tmp_dir/$case_name.metta"
  generate_chain_fixture "$length" "$fixture"
  run_case "$case_name" chain "$length" "$fixture"
done

for width in $fanout_widths; do
  case_name="forward_fanout_$width"
  fixture="$tmp_dir/$case_name.metta"
  generate_fanout_fixture "$width" "$fixture"
  run_case "$case_name" fanout "$width" "$fixture"
done

{
  printf 'case\tshape\tsize\truns\tbaseline_median_ms\tgross_median_ms\tnet_median_ms\tgross_min_ms\tgross_max_ms\tpass\tclose\tfail\tunsupported_ir\tskipped\tstatus\n'
  sort -t $'\t' -k7,7nr "$summary_body"
} > "$summary_report"

cat "$summary_report"
echo "wrote per-run timings to $runs_report"

if [ "$bench_errors" -ne 0 ]; then
  echo "forward benchmark saw $bench_errors non-clean run(s)" >&2
  exit 1
fi
